// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ora/cloud/internal/v1/plugin_executions.proto

package controlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Bounded per-plugin failure codes; raw diagnostics stay in Node logs.
type PluginFailureReason int32

const (
	PluginFailureReason_PLUGIN_FAILURE_REASON_UNSPECIFIED        PluginFailureReason = 0
	PluginFailureReason_PLUGIN_FAILURE_REASON_DOWNLOAD_FAILED    PluginFailureReason = 1
	PluginFailureReason_PLUGIN_FAILURE_REASON_CHECKSUM_MISMATCH  PluginFailureReason = 2
	PluginFailureReason_PLUGIN_FAILURE_REASON_NO_MATCHING_TARGET PluginFailureReason = 3
	PluginFailureReason_PLUGIN_FAILURE_REASON_INVALID_PACKAGE    PluginFailureReason = 4
	PluginFailureReason_PLUGIN_FAILURE_REASON_INSTALL_FAILED     PluginFailureReason = 5
	// A running Agent session uses the plugin, so it was neither replaced nor removed.
	PluginFailureReason_PLUGIN_FAILURE_REASON_PLUGIN_IN_USE PluginFailureReason = 6
)

// Enum value maps for PluginFailureReason.
var (
	PluginFailureReason_name = map[int32]string{
		0: "PLUGIN_FAILURE_REASON_UNSPECIFIED",
		1: "PLUGIN_FAILURE_REASON_DOWNLOAD_FAILED",
		2: "PLUGIN_FAILURE_REASON_CHECKSUM_MISMATCH",
		3: "PLUGIN_FAILURE_REASON_NO_MATCHING_TARGET",
		4: "PLUGIN_FAILURE_REASON_INVALID_PACKAGE",
		5: "PLUGIN_FAILURE_REASON_INSTALL_FAILED",
		6: "PLUGIN_FAILURE_REASON_PLUGIN_IN_USE",
	}
	PluginFailureReason_value = map[string]int32{
		"PLUGIN_FAILURE_REASON_UNSPECIFIED":        0,
		"PLUGIN_FAILURE_REASON_DOWNLOAD_FAILED":    1,
		"PLUGIN_FAILURE_REASON_CHECKSUM_MISMATCH":  2,
		"PLUGIN_FAILURE_REASON_NO_MATCHING_TARGET": 3,
		"PLUGIN_FAILURE_REASON_INVALID_PACKAGE":    4,
		"PLUGIN_FAILURE_REASON_INSTALL_FAILED":     5,
		"PLUGIN_FAILURE_REASON_PLUGIN_IN_USE":      6,
	}
)

func (x PluginFailureReason) Enum() *PluginFailureReason {
	p := new(PluginFailureReason)
	*p = x
	return p
}

func (x PluginFailureReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginFailureReason) Descriptor() protoreflect.EnumDescriptor {
	return file_ora_cloud_internal_v1_plugin_executions_proto_enumTypes[0].Descriptor()
}

func (PluginFailureReason) Type() protoreflect.EnumType {
	return &file_ora_cloud_internal_v1_plugin_executions_proto_enumTypes[0]
}

func (x PluginFailureReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginFailureReason.Descriptor instead.
func (PluginFailureReason) EnumDescriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_plugin_executions_proto_rawDescGZIP(), []int{0}
}

type PluginsFailureReason int32

const (
	PluginsFailureReason_PLUGINS_FAILURE_REASON_UNSPECIFIED PluginsFailureReason = 0
	// The Workspace's plugin root or the Node ledger could not be used.
	PluginsFailureReason_PLUGINS_FAILURE_REASON_PLUGIN_ROOT_UNAVAILABLE PluginsFailureReason = 1
	// Stopped before every item had a result; a new execution may simply retry, since installs are
	// idempotent.
	PluginsFailureReason_PLUGINS_FAILURE_REASON_INTERRUPTED PluginsFailureReason = 2
)

// Enum value maps for PluginsFailureReason.
var (
	PluginsFailureReason_name = map[int32]string{
		0: "PLUGINS_FAILURE_REASON_UNSPECIFIED",
		1: "PLUGINS_FAILURE_REASON_PLUGIN_ROOT_UNAVAILABLE",
		2: "PLUGINS_FAILURE_REASON_INTERRUPTED",
	}
	PluginsFailureReason_value = map[string]int32{
		"PLUGINS_FAILURE_REASON_UNSPECIFIED":             0,
		"PLUGINS_FAILURE_REASON_PLUGIN_ROOT_UNAVAILABLE": 1,
		"PLUGINS_FAILURE_REASON_INTERRUPTED":             2,
	}
)

func (x PluginsFailureReason) Enum() *PluginsFailureReason {
	p := new(PluginsFailureReason)
	*p = x
	return p
}

func (x PluginsFailureReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PluginsFailureReason) Descriptor() protoreflect.EnumDescriptor {
	return file_ora_cloud_internal_v1_plugin_executions_proto_enumTypes[1].Descriptor()
}

func (PluginsFailureReason) Type() protoreflect.EnumType {
	return &file_ora_cloud_internal_v1_plugin_executions_proto_enumTypes[1]
}

func (x PluginsFailureReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PluginsFailureReason.Descriptor instead.
func (PluginsFailureReason) EnumDescriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_plugin_executions_proto_rawDescGZIP(), []int{1}
}

// One download a Node may install from; the SHA-256 is always required and checked before anything
// reaches the plugin root.
type PluginDownload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Url   string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	// Lowercase hexadecimal SHA-256 of the downloaded package.
	Sha256        string `protobuf:"bytes,2,opt,name=sha256,proto3" json:"sha256,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginDownload) Reset() {
	*x = PluginDownload{}
	mi := &file_ora_cloud_internal_v1_plugin_executions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginDownload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginDownload) ProtoMessage() {}

func (x *PluginDownload) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_plugin_executions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginDownload.ProtoReflect.Descriptor instead.
func (*PluginDownload) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_plugin_executions_proto_rawDescGZIP(), []int{0}
}

func (x *PluginDownload) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *PluginDownload) GetSha256() string {
	if x != nil {
		return x.Sha256
	}
	return ""
}

type PluginTargetDownload struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Rust target triple the release was built for.
	Target        string          `protobuf:"bytes,1,opt,name=target,proto3" json:"target,omitempty"`
	Download      *PluginDownload `protobuf:"bytes,2,opt,name=download,proto3" json:"download,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginTargetDownload) Reset() {
	*x = PluginTargetDownload{}
	mi := &file_ora_cloud_internal_v1_plugin_executions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginTargetDownload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginTargetDownload) ProtoMessage() {}

func (x *PluginTargetDownload) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_plugin_executions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginTargetDownload.ProtoReflect.Descriptor instead.
func (*PluginTargetDownload) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_plugin_executions_proto_rawDescGZIP(), []int{1}
}

func (x *PluginTargetDownload) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

func (x *PluginTargetDownload) GetDownload() *PluginDownload {
	if x != nil {
		return x.Download
	}
	return nil
}

// One plugin to install at an exact version. Exactly one of `universal` or a non-empty `targets`
// is set; the Node picks the target matching its own host.
type PluginInstall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Canonical Plugin ID, `<namespace>/<identifier>`.
	PluginId      string                  `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Version       string                  `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Universal     *PluginDownload         `protobuf:"bytes,3,opt,name=universal,proto3,oneof" json:"universal,omitempty"`
	Targets       []*PluginTargetDownload `protobuf:"bytes,4,rep,name=targets,proto3" json:"targets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginInstall) Reset() {
	*x = PluginInstall{}
	mi := &file_ora_cloud_internal_v1_plugin_executions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginInstall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginInstall) ProtoMessage() {}

func (x *PluginInstall) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_plugin_executions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginInstall.ProtoReflect.Descriptor instead.
func (*PluginInstall) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_plugin_executions_proto_rawDescGZIP(), []int{2}
}

func (x *PluginInstall) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *PluginInstall) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *PluginInstall) GetUniversal() *PluginDownload {
	if x != nil {
		return x.Universal
	}
	return nil
}

func (x *PluginInstall) GetTargets() []*PluginTargetDownload {
	if x != nil {
		return x.Targets
	}
	return nil
}

type PluginRemoval struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PluginId      string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginRemoval) Reset() {
	*x = PluginRemoval{}
	mi := &file_ora_cloud_internal_v1_plugin_executions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginRemoval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginRemoval) ProtoMessage() {}

func (x *PluginRemoval) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_plugin_executions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginRemoval.ProtoReflect.Descriptor instead.
func (*PluginRemoval) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_plugin_executions_proto_rawDescGZIP(), []int{3}
}

func (x *PluginRemoval) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *PluginRemoval) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// Installs the plugins into the Workspace's plugin root without starting any of them.
type InstallPluginsSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugins       []*PluginInstall       `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallPluginsSpec) Reset() {
	*x = InstallPluginsSpec{}
	mi := &file_ora_cloud_internal_v1_plugin_executions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallPluginsSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallPluginsSpec) ProtoMessage() {}

func (x *InstallPluginsSpec) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_plugin_executions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallPluginsSpec.ProtoReflect.Descriptor instead.
func (*InstallPluginsSpec) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_plugin_executions_proto_rawDescGZIP(), []int{4}
}

func (x *InstallPluginsSpec) GetPlugins() []*PluginInstall {
	if x != nil {
		return x.Plugins
	}
	return nil
}

type RemovePluginsSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plugins       []*PluginRemoval       `protobuf:"bytes,1,rep,name=plugins,proto3" json:"plugins,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePluginsSpec) Reset() {
	*x = RemovePluginsSpec{}
	mi := &file_ora_cloud_internal_v1_plugin_executions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePluginsSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePluginsSpec) ProtoMessage() {}

func (x *RemovePluginsSpec) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_plugin_executions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePluginsSpec.ProtoReflect.Descriptor instead.
func (*RemovePluginsSpec) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_plugin_executions_proto_rawDescGZIP(), []int{5}
}

func (x *RemovePluginsSpec) GetPlugins() []*PluginRemoval {
	if x != nil {
		return x.Plugins
	}
	return nil
}

type PluginItemInstalled struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Must equal the planned version; Cloud refuses the whole result otherwise.
	Version       string `protobuf:"bytes,1,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginItemInstalled) Reset() {
	*x = PluginItemInstalled{}
	mi := &file_ora_cloud_internal_v1_plugin_executions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginItemInstalled) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginItemInstalled) ProtoMessage() {}

func (x *PluginItemInstalled) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_plugin_executions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginItemInstalled.ProtoReflect.Descriptor instead.
func (*PluginItemInstalled) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_plugin_executions_proto_rawDescGZIP(), []int{6}
}

func (x *PluginItemInstalled) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

type PluginItemRemoved struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginItemRemoved) Reset() {
	*x = PluginItemRemoved{}
	mi := &file_ora_cloud_internal_v1_plugin_executions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginItemRemoved) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginItemRemoved) ProtoMessage() {}

func (x *PluginItemRemoved) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_plugin_executions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginItemRemoved.ProtoReflect.Descriptor instead.
func (*PluginItemRemoved) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_plugin_executions_proto_rawDescGZIP(), []int{7}
}

type PluginItemFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        PluginFailureReason    `protobuf:"varint,1,opt,name=reason,proto3,enum=ora.cloud.internal.v1.PluginFailureReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginItemFailed) Reset() {
	*x = PluginItemFailed{}
	mi := &file_ora_cloud_internal_v1_plugin_executions_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginItemFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginItemFailed) ProtoMessage() {}

func (x *PluginItemFailed) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_plugin_executions_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginItemFailed.ProtoReflect.Descriptor instead.
func (*PluginItemFailed) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_plugin_executions_proto_rawDescGZIP(), []int{8}
}

func (x *PluginItemFailed) GetReason() PluginFailureReason {
	if x != nil {
		return x.Reason
	}
	return PluginFailureReason_PLUGIN_FAILURE_REASON_UNSPECIFIED
}

type PluginItemResult struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	PluginId string                 `protobuf:"bytes,1,opt,name=plugin_id,json=pluginId,proto3" json:"plugin_id,omitempty"`
	// Types that are valid to be assigned to Outcome:
	//
	//	*PluginItemResult_Installed
	//	*PluginItemResult_Removed
	//	*PluginItemResult_Failed
	Outcome       isPluginItemResult_Outcome `protobuf_oneof:"outcome"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginItemResult) Reset() {
	*x = PluginItemResult{}
	mi := &file_ora_cloud_internal_v1_plugin_executions_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginItemResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginItemResult) ProtoMessage() {}

func (x *PluginItemResult) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_plugin_executions_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginItemResult.ProtoReflect.Descriptor instead.
func (*PluginItemResult) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_plugin_executions_proto_rawDescGZIP(), []int{9}
}

func (x *PluginItemResult) GetPluginId() string {
	if x != nil {
		return x.PluginId
	}
	return ""
}

func (x *PluginItemResult) GetOutcome() isPluginItemResult_Outcome {
	if x != nil {
		return x.Outcome
	}
	return nil
}

func (x *PluginItemResult) GetInstalled() *PluginItemInstalled {
	if x != nil {
		if x, ok := x.Outcome.(*PluginItemResult_Installed); ok {
			return x.Installed
		}
	}
	return nil
}

func (x *PluginItemResult) GetRemoved() *PluginItemRemoved {
	if x != nil {
		if x, ok := x.Outcome.(*PluginItemResult_Removed); ok {
			return x.Removed
		}
	}
	return nil
}

func (x *PluginItemResult) GetFailed() *PluginItemFailed {
	if x != nil {
		if x, ok := x.Outcome.(*PluginItemResult_Failed); ok {
			return x.Failed
		}
	}
	return nil
}

type isPluginItemResult_Outcome interface {
	isPluginItemResult_Outcome()
}

type PluginItemResult_Installed struct {
	Installed *PluginItemInstalled `protobuf:"bytes,2,opt,name=installed,proto3,oneof"`
}

type PluginItemResult_Removed struct {
	Removed *PluginItemRemoved `protobuf:"bytes,3,opt,name=removed,proto3,oneof"`
}

type PluginItemResult_Failed struct {
	Failed *PluginItemFailed `protobuf:"bytes,4,opt,name=failed,proto3,oneof"`
}

func (*PluginItemResult_Installed) isPluginItemResult_Outcome() {}

func (*PluginItemResult_Removed) isPluginItemResult_Outcome() {}

func (*PluginItemResult_Failed) isPluginItemResult_Outcome() {}

// Terminal result of a plugin execution: one item per planned plugin. A failed item does not fail
// the execution; only an execution-level failure (the Node could not run it at all) does.
type PluginsResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*PluginItemResult    `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginsResult) Reset() {
	*x = PluginsResult{}
	mi := &file_ora_cloud_internal_v1_plugin_executions_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginsResult) ProtoMessage() {}

func (x *PluginsResult) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_plugin_executions_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginsResult.ProtoReflect.Descriptor instead.
func (*PluginsResult) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_plugin_executions_proto_rawDescGZIP(), []int{10}
}

func (x *PluginsResult) GetItems() []*PluginItemResult {
	if x != nil {
		return x.Items
	}
	return nil
}

// Terminal result when the execution as a whole could not run; no item is reported.
type PluginsFailed struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reason        PluginsFailureReason   `protobuf:"varint,1,opt,name=reason,proto3,enum=ora.cloud.internal.v1.PluginsFailureReason" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PluginsFailed) Reset() {
	*x = PluginsFailed{}
	mi := &file_ora_cloud_internal_v1_plugin_executions_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PluginsFailed) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PluginsFailed) ProtoMessage() {}

func (x *PluginsFailed) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_plugin_executions_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PluginsFailed.ProtoReflect.Descriptor instead.
func (*PluginsFailed) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_plugin_executions_proto_rawDescGZIP(), []int{11}
}

func (x *PluginsFailed) GetReason() PluginsFailureReason {
	if x != nil {
		return x.Reason
	}
	return PluginsFailureReason_PLUGINS_FAILURE_REASON_UNSPECIFIED
}

var File_ora_cloud_internal_v1_plugin_executions_proto protoreflect.FileDescriptor

const file_ora_cloud_internal_v1_plugin_executions_proto_rawDesc = "" +
	"\n" +
	"-ora/cloud/internal/v1/plugin_executions.proto\x12\x15ora.cloud.internal.v1\":\n" +
	"\x0ePluginDownload\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\x16\n" +
	"\x06sha256\x18\x02 \x01(\tR\x06sha256\"q\n" +
	"\x14PluginTargetDownload\x12\x16\n" +
	"\x06target\x18\x01 \x01(\tR\x06target\x12A\n" +
	"\bdownload\x18\x02 \x01(\v2%.ora.cloud.internal.v1.PluginDownloadR\bdownload\"\xe5\x01\n" +
	"\rPluginInstall\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12H\n" +
	"\tuniversal\x18\x03 \x01(\v2%.ora.cloud.internal.v1.PluginDownloadH\x00R\tuniversal\x88\x01\x01\x12E\n" +
	"\atargets\x18\x04 \x03(\v2+.ora.cloud.internal.v1.PluginTargetDownloadR\atargetsB\f\n" +
	"\n" +
	"_universal\"F\n" +
	"\rPluginRemoval\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\"T\n" +
	"\x12InstallPluginsSpec\x12>\n" +
	"\aplugins\x18\x01 \x03(\v2$.ora.cloud.internal.v1.PluginInstallR\aplugins\"S\n" +
	"\x11RemovePluginsSpec\x12>\n" +
	"\aplugins\x18\x01 \x03(\v2$.ora.cloud.internal.v1.PluginRemovalR\aplugins\"/\n" +
	"\x13PluginItemInstalled\x12\x18\n" +
	"\aversion\x18\x01 \x01(\tR\aversion\"\x13\n" +
	"\x11PluginItemRemoved\"V\n" +
	"\x10PluginItemFailed\x12B\n" +
	"\x06reason\x18\x01 \x01(\x0e2*.ora.cloud.internal.v1.PluginFailureReasonR\x06reason\"\x8f\x02\n" +
	"\x10PluginItemResult\x12\x1b\n" +
	"\tplugin_id\x18\x01 \x01(\tR\bpluginId\x12J\n" +
	"\tinstalled\x18\x02 \x01(\v2*.ora.cloud.internal.v1.PluginItemInstalledH\x00R\tinstalled\x12D\n" +
	"\aremoved\x18\x03 \x01(\v2(.ora.cloud.internal.v1.PluginItemRemovedH\x00R\aremoved\x12A\n" +
	"\x06failed\x18\x04 \x01(\v2'.ora.cloud.internal.v1.PluginItemFailedH\x00R\x06failedB\t\n" +
	"\aoutcome\"N\n" +
	"\rPluginsResult\x12=\n" +
	"\x05items\x18\x01 \x03(\v2'.ora.cloud.internal.v1.PluginItemResultR\x05items\"T\n" +
	"\rPluginsFailed\x12C\n" +
	"\x06reason\x18\x01 \x01(\x0e2+.ora.cloud.internal.v1.PluginsFailureReasonR\x06reason*\xc0\x02\n" +
	"\x13PluginFailureReason\x12%\n" +
	"!PLUGIN_FAILURE_REASON_UNSPECIFIED\x10\x00\x12)\n" +
	"%PLUGIN_FAILURE_REASON_DOWNLOAD_FAILED\x10\x01\x12+\n" +
	"'PLUGIN_FAILURE_REASON_CHECKSUM_MISMATCH\x10\x02\x12,\n" +
	"(PLUGIN_FAILURE_REASON_NO_MATCHING_TARGET\x10\x03\x12)\n" +
	"%PLUGIN_FAILURE_REASON_INVALID_PACKAGE\x10\x04\x12(\n" +
	"$PLUGIN_FAILURE_REASON_INSTALL_FAILED\x10\x05\x12'\n" +
	"#PLUGIN_FAILURE_REASON_PLUGIN_IN_USE\x10\x06*\x9a\x01\n" +
	"\x14PluginsFailureReason\x12&\n" +
	"\"PLUGINS_FAILURE_REASON_UNSPECIFIED\x10\x00\x122\n" +
	".PLUGINS_FAILURE_REASON_PLUGIN_ROOT_UNAVAILABLE\x10\x01\x12&\n" +
	"\"PLUGINS_FAILURE_REASON_INTERRUPTED\x10\x02B\xe6\x01\n" +
	"\x19com.ora.cloud.internal.v1B\x15PluginExecutionsProtoP\x01Z;github.com/wanglongan587/cloud/internal/controlpb;controlpb\xa2\x02\x03OCI\xaa\x02\x15Ora.Cloud.Internal.V1\xca\x02\x15Ora\\Cloud\\Internal\\V1\xe2\x02!Ora\\Cloud\\Internal\\V1\\GPBMetadata\xea\x02\x18Ora::Cloud::Internal::V1b\x06proto3"

var (
	file_ora_cloud_internal_v1_plugin_executions_proto_rawDescOnce sync.Once
	file_ora_cloud_internal_v1_plugin_executions_proto_rawDescData []byte
)

func file_ora_cloud_internal_v1_plugin_executions_proto_rawDescGZIP() []byte {
	file_ora_cloud_internal_v1_plugin_executions_proto_rawDescOnce.Do(func() {
		file_ora_cloud_internal_v1_plugin_executions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ora_cloud_internal_v1_plugin_executions_proto_rawDesc), len(file_ora_cloud_internal_v1_plugin_executions_proto_rawDesc)))
	})
	return file_ora_cloud_internal_v1_plugin_executions_proto_rawDescData
}

var file_ora_cloud_internal_v1_plugin_executions_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ora_cloud_internal_v1_plugin_executions_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_ora_cloud_internal_v1_plugin_executions_proto_goTypes = []any{
	(PluginFailureReason)(0),     // 0: ora.cloud.internal.v1.PluginFailureReason
	(PluginsFailureReason)(0),    // 1: ora.cloud.internal.v1.PluginsFailureReason
	(*PluginDownload)(nil),       // 2: ora.cloud.internal.v1.PluginDownload
	(*PluginTargetDownload)(nil), // 3: ora.cloud.internal.v1.PluginTargetDownload
	(*PluginInstall)(nil),        // 4: ora.cloud.internal.v1.PluginInstall
	(*PluginRemoval)(nil),        // 5: ora.cloud.internal.v1.PluginRemoval
	(*InstallPluginsSpec)(nil),   // 6: ora.cloud.internal.v1.InstallPluginsSpec
	(*RemovePluginsSpec)(nil),    // 7: ora.cloud.internal.v1.RemovePluginsSpec
	(*PluginItemInstalled)(nil),  // 8: ora.cloud.internal.v1.PluginItemInstalled
	(*PluginItemRemoved)(nil),    // 9: ora.cloud.internal.v1.PluginItemRemoved
	(*PluginItemFailed)(nil),     // 10: ora.cloud.internal.v1.PluginItemFailed
	(*PluginItemResult)(nil),     // 11: ora.cloud.internal.v1.PluginItemResult
	(*PluginsResult)(nil),        // 12: ora.cloud.internal.v1.PluginsResult
	(*PluginsFailed)(nil),        // 13: ora.cloud.internal.v1.PluginsFailed
}
var file_ora_cloud_internal_v1_plugin_executions_proto_depIdxs = []int32{
	2,  // 0: ora.cloud.internal.v1.PluginTargetDownload.download:type_name -> ora.cloud.internal.v1.PluginDownload
	2,  // 1: ora.cloud.internal.v1.PluginInstall.universal:type_name -> ora.cloud.internal.v1.PluginDownload
	3,  // 2: ora.cloud.internal.v1.PluginInstall.targets:type_name -> ora.cloud.internal.v1.PluginTargetDownload
	4,  // 3: ora.cloud.internal.v1.InstallPluginsSpec.plugins:type_name -> ora.cloud.internal.v1.PluginInstall
	5,  // 4: ora.cloud.internal.v1.RemovePluginsSpec.plugins:type_name -> ora.cloud.internal.v1.PluginRemoval
	0,  // 5: ora.cloud.internal.v1.PluginItemFailed.reason:type_name -> ora.cloud.internal.v1.PluginFailureReason
	8,  // 6: ora.cloud.internal.v1.PluginItemResult.installed:type_name -> ora.cloud.internal.v1.PluginItemInstalled
	9,  // 7: ora.cloud.internal.v1.PluginItemResult.removed:type_name -> ora.cloud.internal.v1.PluginItemRemoved
	10, // 8: ora.cloud.internal.v1.PluginItemResult.failed:type_name -> ora.cloud.internal.v1.PluginItemFailed
	11, // 9: ora.cloud.internal.v1.PluginsResult.items:type_name -> ora.cloud.internal.v1.PluginItemResult
	1,  // 10: ora.cloud.internal.v1.PluginsFailed.reason:type_name -> ora.cloud.internal.v1.PluginsFailureReason
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_ora_cloud_internal_v1_plugin_executions_proto_init() }
func file_ora_cloud_internal_v1_plugin_executions_proto_init() {
	if File_ora_cloud_internal_v1_plugin_executions_proto != nil {
		return
	}
	file_ora_cloud_internal_v1_plugin_executions_proto_msgTypes[2].OneofWrappers = []any{}
	file_ora_cloud_internal_v1_plugin_executions_proto_msgTypes[9].OneofWrappers = []any{
		(*PluginItemResult_Installed)(nil),
		(*PluginItemResult_Removed)(nil),
		(*PluginItemResult_Failed)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ora_cloud_internal_v1_plugin_executions_proto_rawDesc), len(file_ora_cloud_internal_v1_plugin_executions_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ora_cloud_internal_v1_plugin_executions_proto_goTypes,
		DependencyIndexes: file_ora_cloud_internal_v1_plugin_executions_proto_depIdxs,
		EnumInfos:         file_ora_cloud_internal_v1_plugin_executions_proto_enumTypes,
		MessageInfos:      file_ora_cloud_internal_v1_plugin_executions_proto_msgTypes,
	}.Build()
	File_ora_cloud_internal_v1_plugin_executions_proto = out.File
	file_ora_cloud_internal_v1_plugin_executions_proto_goTypes = nil
	file_ora_cloud_internal_v1_plugin_executions_proto_depIdxs = nil
}
