// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: ora/cloud/internal/v1/runtime_control.proto

package controlpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RuntimeControlService_ListBindings_FullMethodName       = "/ora.cloud.internal.v1.RuntimeControlService/ListBindings"
	RuntimeControlService_AcknowledgeBinding_FullMethodName = "/ora.cloud.internal.v1.RuntimeControlService/AcknowledgeBinding"
	RuntimeControlService_GetExecutionPermit_FullMethodName = "/ora.cloud.internal.v1.RuntimeControlService/GetExecutionPermit"
)

// RuntimeControlServiceClient is the client API for RuntimeControlService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Mandatory for controlled cloud execution. Legacy participants must refuse execution when this
// service or the Node runtime_control capability is unavailable, without falling back to raw clone.
type RuntimeControlServiceClient interface {
	ListBindings(ctx context.Context, in *ListRuntimeBindingsRequest, opts ...grpc.CallOption) (*ListRuntimeBindingsResponse, error)
	AcknowledgeBinding(ctx context.Context, in *AcknowledgeRuntimeBindingRequest, opts ...grpc.CallOption) (*AcknowledgeRuntimeBindingResponse, error)
	// Read-only and intentionally not submission-replayed: every dispatch obtains current authority.
	GetExecutionPermit(ctx context.Context, in *GetRuntimeExecutionPermitRequest, opts ...grpc.CallOption) (*GetRuntimeExecutionPermitResponse, error)
}

type runtimeControlServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRuntimeControlServiceClient(cc grpc.ClientConnInterface) RuntimeControlServiceClient {
	return &runtimeControlServiceClient{cc}
}

func (c *runtimeControlServiceClient) ListBindings(ctx context.Context, in *ListRuntimeBindingsRequest, opts ...grpc.CallOption) (*ListRuntimeBindingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRuntimeBindingsResponse)
	err := c.cc.Invoke(ctx, RuntimeControlService_ListBindings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeControlServiceClient) AcknowledgeBinding(ctx context.Context, in *AcknowledgeRuntimeBindingRequest, opts ...grpc.CallOption) (*AcknowledgeRuntimeBindingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcknowledgeRuntimeBindingResponse)
	err := c.cc.Invoke(ctx, RuntimeControlService_AcknowledgeBinding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *runtimeControlServiceClient) GetExecutionPermit(ctx context.Context, in *GetRuntimeExecutionPermitRequest, opts ...grpc.CallOption) (*GetRuntimeExecutionPermitResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRuntimeExecutionPermitResponse)
	err := c.cc.Invoke(ctx, RuntimeControlService_GetExecutionPermit_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuntimeControlServiceServer is the server API for RuntimeControlService service.
// All implementations must embed UnimplementedRuntimeControlServiceServer
// for forward compatibility.
//
// Mandatory for controlled cloud execution. Legacy participants must refuse execution when this
// service or the Node runtime_control capability is unavailable, without falling back to raw clone.
type RuntimeControlServiceServer interface {
	ListBindings(context.Context, *ListRuntimeBindingsRequest) (*ListRuntimeBindingsResponse, error)
	AcknowledgeBinding(context.Context, *AcknowledgeRuntimeBindingRequest) (*AcknowledgeRuntimeBindingResponse, error)
	// Read-only and intentionally not submission-replayed: every dispatch obtains current authority.
	GetExecutionPermit(context.Context, *GetRuntimeExecutionPermitRequest) (*GetRuntimeExecutionPermitResponse, error)
	mustEmbedUnimplementedRuntimeControlServiceServer()
}

// UnimplementedRuntimeControlServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuntimeControlServiceServer struct{}

func (UnimplementedRuntimeControlServiceServer) ListBindings(context.Context, *ListRuntimeBindingsRequest) (*ListRuntimeBindingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBindings not implemented")
}
func (UnimplementedRuntimeControlServiceServer) AcknowledgeBinding(context.Context, *AcknowledgeRuntimeBindingRequest) (*AcknowledgeRuntimeBindingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcknowledgeBinding not implemented")
}
func (UnimplementedRuntimeControlServiceServer) GetExecutionPermit(context.Context, *GetRuntimeExecutionPermitRequest) (*GetRuntimeExecutionPermitResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetExecutionPermit not implemented")
}
func (UnimplementedRuntimeControlServiceServer) mustEmbedUnimplementedRuntimeControlServiceServer() {}
func (UnimplementedRuntimeControlServiceServer) testEmbeddedByValue()                               {}

// UnsafeRuntimeControlServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuntimeControlServiceServer will
// result in compilation errors.
type UnsafeRuntimeControlServiceServer interface {
	mustEmbedUnimplementedRuntimeControlServiceServer()
}

func RegisterRuntimeControlServiceServer(s grpc.ServiceRegistrar, srv RuntimeControlServiceServer) {
	// If the following call pancis, it indicates UnimplementedRuntimeControlServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RuntimeControlService_ServiceDesc, srv)
}

func _RuntimeControlService_ListBindings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRuntimeBindingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeControlServiceServer).ListBindings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeControlService_ListBindings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeControlServiceServer).ListBindings(ctx, req.(*ListRuntimeBindingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeControlService_AcknowledgeBinding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcknowledgeRuntimeBindingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeControlServiceServer).AcknowledgeBinding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeControlService_AcknowledgeBinding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeControlServiceServer).AcknowledgeBinding(ctx, req.(*AcknowledgeRuntimeBindingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RuntimeControlService_GetExecutionPermit_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRuntimeExecutionPermitRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeControlServiceServer).GetExecutionPermit(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeControlService_GetExecutionPermit_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeControlServiceServer).GetExecutionPermit(ctx, req.(*GetRuntimeExecutionPermitRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RuntimeControlService_ServiceDesc is the grpc.ServiceDesc for RuntimeControlService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuntimeControlService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ora.cloud.internal.v1.RuntimeControlService",
	HandlerType: (*RuntimeControlServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBindings",
			Handler:    _RuntimeControlService_ListBindings_Handler,
		},
		{
			MethodName: "AcknowledgeBinding",
			Handler:    _RuntimeControlService_AcknowledgeBinding_Handler,
		},
		{
			MethodName: "GetExecutionPermit",
			Handler:    _RuntimeControlService_GetExecutionPermit_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ora/cloud/internal/v1/runtime_control.proto",
}
