// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ora/cloud/internal/v1/runtime_control.proto

package controlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordControlDispatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Caller-chosen retry identity. The same id with different content conflicts.
	SubmissionId string `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	// Controller lease epoch. It fences the coordinator, not the user session.
	Epoch int64 `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	// Stable execution identity. A retry must reuse it and must not mint another.
	ExecutionId string `protobuf:"bytes,3,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	// Runtime the execution is bound to. Cloud loads the tenant from this row.
	WorkspaceId string `protobuf:"bytes,4,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	// Runtime control epoch of the held session. Not the controller lease epoch.
	ControlEpoch int64 `protobuf:"varint,5,opt,name=control_epoch,json=controlEpoch,proto3" json:"control_epoch,omitempty"`
	// Runtime generation the execution is pinned to.
	RuntimeGeneration int64 `protobuf:"varint,6,opt,name=runtime_generation,json=runtimeGeneration,proto3" json:"runtime_generation,omitempty"`
	// Fixed input. Only a clone spec is accepted; other kinds stay closed.
	Input *ExecutionInput `protobuf:"bytes,7,opt,name=input,proto3" json:"input,omitempty"`
	// Must be 2. Zero is the old protocol and is refused.
	ProtocolGeneration uint32 `protobuf:"varint,8,opt,name=protocol_generation,json=protocolGeneration,proto3" json:"protocol_generation,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RecordControlDispatchRequest) Reset() {
	*x = RecordControlDispatchRequest{}
	mi := &file_ora_cloud_internal_v1_runtime_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordControlDispatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordControlDispatchRequest) ProtoMessage() {}

func (x *RecordControlDispatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_runtime_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordControlDispatchRequest.ProtoReflect.Descriptor instead.
func (*RecordControlDispatchRequest) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_runtime_control_proto_rawDescGZIP(), []int{0}
}

func (x *RecordControlDispatchRequest) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *RecordControlDispatchRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *RecordControlDispatchRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *RecordControlDispatchRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *RecordControlDispatchRequest) GetControlEpoch() int64 {
	if x != nil {
		return x.ControlEpoch
	}
	return 0
}

func (x *RecordControlDispatchRequest) GetRuntimeGeneration() int64 {
	if x != nil {
		return x.RuntimeGeneration
	}
	return 0
}

func (x *RecordControlDispatchRequest) GetInput() *ExecutionInput {
	if x != nil {
		return x.Input
	}
	return nil
}

func (x *RecordControlDispatchRequest) GetProtocolGeneration() uint32 {
	if x != nil {
		return x.ProtocolGeneration
	}
	return 0
}

// The durable dispatch record. It carries no user id and no secret.
type ControlDispatch struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ExecutionId       string                 `protobuf:"bytes,1,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	WorkspaceId       string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	ControlEpoch      int64                  `protobuf:"varint,3,opt,name=control_epoch,json=controlEpoch,proto3" json:"control_epoch,omitempty"`
	RuntimeGeneration int64                  `protobuf:"varint,4,opt,name=runtime_generation,json=runtimeGeneration,proto3" json:"runtime_generation,omitempty"`
	Input             *ExecutionInput        `protobuf:"bytes,5,opt,name=input,proto3" json:"input,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ControlDispatch) Reset() {
	*x = ControlDispatch{}
	mi := &file_ora_cloud_internal_v1_runtime_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlDispatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlDispatch) ProtoMessage() {}

func (x *ControlDispatch) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_runtime_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlDispatch.ProtoReflect.Descriptor instead.
func (*ControlDispatch) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_runtime_control_proto_rawDescGZIP(), []int{1}
}

func (x *ControlDispatch) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *ControlDispatch) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *ControlDispatch) GetControlEpoch() int64 {
	if x != nil {
		return x.ControlEpoch
	}
	return 0
}

func (x *ControlDispatch) GetRuntimeGeneration() int64 {
	if x != nil {
		return x.RuntimeGeneration
	}
	return 0
}

func (x *ControlDispatch) GetInput() *ExecutionInput {
	if x != nil {
		return x.Input
	}
	return nil
}

type RecordControlDispatchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dispatch      *ControlDispatch       `protobuf:"bytes,1,opt,name=dispatch,proto3" json:"dispatch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordControlDispatchResponse) Reset() {
	*x = RecordControlDispatchResponse{}
	mi := &file_ora_cloud_internal_v1_runtime_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordControlDispatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordControlDispatchResponse) ProtoMessage() {}

func (x *RecordControlDispatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_runtime_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordControlDispatchResponse.ProtoReflect.Descriptor instead.
func (*RecordControlDispatchResponse) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_runtime_control_proto_rawDescGZIP(), []int{2}
}

func (x *RecordControlDispatchResponse) GetDispatch() *ControlDispatch {
	if x != nil {
		return x.Dispatch
	}
	return nil
}

var File_ora_cloud_internal_v1_runtime_control_proto protoreflect.FileDescriptor

const file_ora_cloud_internal_v1_runtime_control_proto_rawDesc = "" +
	"\n" +
	"+ora/cloud/internal/v1/runtime_control.proto\x12\x15ora.cloud.internal.v1\x1a&ora/cloud/internal/v1/executions.proto\"\xe1\x02\n" +
	"\x1cRecordControlDispatchRequest\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x03R\x05epoch\x12!\n" +
	"\fexecution_id\x18\x03 \x01(\tR\vexecutionId\x12!\n" +
	"\fworkspace_id\x18\x04 \x01(\tR\vworkspaceId\x12#\n" +
	"\rcontrol_epoch\x18\x05 \x01(\x03R\fcontrolEpoch\x12-\n" +
	"\x12runtime_generation\x18\x06 \x01(\x03R\x11runtimeGeneration\x12;\n" +
	"\x05input\x18\a \x01(\v2%.ora.cloud.internal.v1.ExecutionInputR\x05input\x12/\n" +
	"\x13protocol_generation\x18\b \x01(\rR\x12protocolGeneration\"\xe8\x01\n" +
	"\x0fControlDispatch\x12!\n" +
	"\fexecution_id\x18\x01 \x01(\tR\vexecutionId\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12#\n" +
	"\rcontrol_epoch\x18\x03 \x01(\x03R\fcontrolEpoch\x12-\n" +
	"\x12runtime_generation\x18\x04 \x01(\x03R\x11runtimeGeneration\x12;\n" +
	"\x05input\x18\x05 \x01(\v2%.ora.cloud.internal.v1.ExecutionInputR\x05input\"c\n" +
	"\x1dRecordControlDispatchResponse\x12B\n" +
	"\bdispatch\x18\x01 \x01(\v2&.ora.cloud.internal.v1.ControlDispatchR\bdispatch2\xa4\x01\n" +
	"\x1dRuntimeControlDeliveryService\x12\x82\x01\n" +
	"\x15RecordControlDispatch\x123.ora.cloud.internal.v1.RecordControlDispatchRequest\x1a4.ora.cloud.internal.v1.RecordControlDispatchResponseB\xe4\x01\n" +
	"\x19com.ora.cloud.internal.v1B\x13RuntimeControlProtoP\x01Z;github.com/wanglongan587/cloud/internal/controlpb;controlpb\xa2\x02\x03OCI\xaa\x02\x15Ora.Cloud.Internal.V1\xca\x02\x15Ora\\Cloud\\Internal\\V1\xe2\x02!Ora\\Cloud\\Internal\\V1\\GPBMetadata\xea\x02\x18Ora::Cloud::Internal::V1b\x06proto3"

var (
	file_ora_cloud_internal_v1_runtime_control_proto_rawDescOnce sync.Once
	file_ora_cloud_internal_v1_runtime_control_proto_rawDescData []byte
)

func file_ora_cloud_internal_v1_runtime_control_proto_rawDescGZIP() []byte {
	file_ora_cloud_internal_v1_runtime_control_proto_rawDescOnce.Do(func() {
		file_ora_cloud_internal_v1_runtime_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ora_cloud_internal_v1_runtime_control_proto_rawDesc), len(file_ora_cloud_internal_v1_runtime_control_proto_rawDesc)))
	})
	return file_ora_cloud_internal_v1_runtime_control_proto_rawDescData
}

var file_ora_cloud_internal_v1_runtime_control_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_ora_cloud_internal_v1_runtime_control_proto_goTypes = []any{
	(*RecordControlDispatchRequest)(nil),  // 0: ora.cloud.internal.v1.RecordControlDispatchRequest
	(*ControlDispatch)(nil),               // 1: ora.cloud.internal.v1.ControlDispatch
	(*RecordControlDispatchResponse)(nil), // 2: ora.cloud.internal.v1.RecordControlDispatchResponse
	(*ExecutionInput)(nil),                // 3: ora.cloud.internal.v1.ExecutionInput
}
var file_ora_cloud_internal_v1_runtime_control_proto_depIdxs = []int32{
	3, // 0: ora.cloud.internal.v1.RecordControlDispatchRequest.input:type_name -> ora.cloud.internal.v1.ExecutionInput
	3, // 1: ora.cloud.internal.v1.ControlDispatch.input:type_name -> ora.cloud.internal.v1.ExecutionInput
	1, // 2: ora.cloud.internal.v1.RecordControlDispatchResponse.dispatch:type_name -> ora.cloud.internal.v1.ControlDispatch
	0, // 3: ora.cloud.internal.v1.RuntimeControlDeliveryService.RecordControlDispatch:input_type -> ora.cloud.internal.v1.RecordControlDispatchRequest
	2, // 4: ora.cloud.internal.v1.RuntimeControlDeliveryService.RecordControlDispatch:output_type -> ora.cloud.internal.v1.RecordControlDispatchResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_ora_cloud_internal_v1_runtime_control_proto_init() }
func file_ora_cloud_internal_v1_runtime_control_proto_init() {
	if File_ora_cloud_internal_v1_runtime_control_proto != nil {
		return
	}
	file_ora_cloud_internal_v1_executions_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ora_cloud_internal_v1_runtime_control_proto_rawDesc), len(file_ora_cloud_internal_v1_runtime_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ora_cloud_internal_v1_runtime_control_proto_goTypes,
		DependencyIndexes: file_ora_cloud_internal_v1_runtime_control_proto_depIdxs,
		MessageInfos:      file_ora_cloud_internal_v1_runtime_control_proto_msgTypes,
	}.Build()
	File_ora_cloud_internal_v1_runtime_control_proto = out.File
	file_ora_cloud_internal_v1_runtime_control_proto_goTypes = nil
	file_ora_cloud_internal_v1_runtime_control_proto_depIdxs = nil
}
