// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: ora/cloud/internal/v1/runtime_control.proto

package controlpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RuntimeControlDeliveryService_RecordControlDispatch_FullMethodName = "/ora.cloud.internal.v1.RuntimeControlDeliveryService/RecordControlDispatch"
)

// RuntimeControlDeliveryServiceClient is the client API for RuntimeControlDeliveryService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Runtime-control delivery. Protocol generation 2 is required. A caller that
// omits it, or sends any other generation, is the old protocol and is refused.
// Declaring a ControllerId does not authenticate this service. Until deployment
// mutual TLS binds a service identity to the controller and the target runtime,
// Cloud keeps the capability closed and records no dispatch.
type RuntimeControlDeliveryServiceClient interface {
	// Records one execution before anything is sent onward. The same submission
	// and the same execution identity with the same input return the original
	// record. Cloud does not start a Node, install a plugin, or mark a runtime
	// stopped.
	RecordControlDispatch(ctx context.Context, in *RecordControlDispatchRequest, opts ...grpc.CallOption) (*RecordControlDispatchResponse, error)
}

type runtimeControlDeliveryServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRuntimeControlDeliveryServiceClient(cc grpc.ClientConnInterface) RuntimeControlDeliveryServiceClient {
	return &runtimeControlDeliveryServiceClient{cc}
}

func (c *runtimeControlDeliveryServiceClient) RecordControlDispatch(ctx context.Context, in *RecordControlDispatchRequest, opts ...grpc.CallOption) (*RecordControlDispatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecordControlDispatchResponse)
	err := c.cc.Invoke(ctx, RuntimeControlDeliveryService_RecordControlDispatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RuntimeControlDeliveryServiceServer is the server API for RuntimeControlDeliveryService service.
// All implementations must embed UnimplementedRuntimeControlDeliveryServiceServer
// for forward compatibility.
//
// Runtime-control delivery. Protocol generation 2 is required. A caller that
// omits it, or sends any other generation, is the old protocol and is refused.
// Declaring a ControllerId does not authenticate this service. Until deployment
// mutual TLS binds a service identity to the controller and the target runtime,
// Cloud keeps the capability closed and records no dispatch.
type RuntimeControlDeliveryServiceServer interface {
	// Records one execution before anything is sent onward. The same submission
	// and the same execution identity with the same input return the original
	// record. Cloud does not start a Node, install a plugin, or mark a runtime
	// stopped.
	RecordControlDispatch(context.Context, *RecordControlDispatchRequest) (*RecordControlDispatchResponse, error)
	mustEmbedUnimplementedRuntimeControlDeliveryServiceServer()
}

// UnimplementedRuntimeControlDeliveryServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRuntimeControlDeliveryServiceServer struct{}

func (UnimplementedRuntimeControlDeliveryServiceServer) RecordControlDispatch(context.Context, *RecordControlDispatchRequest) (*RecordControlDispatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RecordControlDispatch not implemented")
}
func (UnimplementedRuntimeControlDeliveryServiceServer) mustEmbedUnimplementedRuntimeControlDeliveryServiceServer() {
}
func (UnimplementedRuntimeControlDeliveryServiceServer) testEmbeddedByValue() {}

// UnsafeRuntimeControlDeliveryServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RuntimeControlDeliveryServiceServer will
// result in compilation errors.
type UnsafeRuntimeControlDeliveryServiceServer interface {
	mustEmbedUnimplementedRuntimeControlDeliveryServiceServer()
}

func RegisterRuntimeControlDeliveryServiceServer(s grpc.ServiceRegistrar, srv RuntimeControlDeliveryServiceServer) {
	// If the following call pancis, it indicates UnimplementedRuntimeControlDeliveryServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RuntimeControlDeliveryService_ServiceDesc, srv)
}

func _RuntimeControlDeliveryService_RecordControlDispatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecordControlDispatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RuntimeControlDeliveryServiceServer).RecordControlDispatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RuntimeControlDeliveryService_RecordControlDispatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RuntimeControlDeliveryServiceServer).RecordControlDispatch(ctx, req.(*RecordControlDispatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RuntimeControlDeliveryService_ServiceDesc is the grpc.ServiceDesc for RuntimeControlDeliveryService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RuntimeControlDeliveryService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ora.cloud.internal.v1.RuntimeControlDeliveryService",
	HandlerType: (*RuntimeControlDeliveryServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RecordControlDispatch",
			Handler:    _RuntimeControlDeliveryService_RecordControlDispatch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "ora/cloud/internal/v1/runtime_control.proto",
}
