// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ora/cloud/internal/v1/runtime_control.proto

package controlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Scope allocated by Cloud. Epochs name different authorities; none substitutes for another.
type RuntimeBinding struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TenantId          string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	WorkspaceId       string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	SandboxId         string                 `protobuf:"bytes,3,opt,name=sandbox_id,json=sandboxId,proto3" json:"sandbox_id,omitempty"`
	RuntimeGeneration int64                  `protobuf:"varint,4,opt,name=runtime_generation,json=runtimeGeneration,proto3" json:"runtime_generation,omitempty"`
	NodeId            string                 `protobuf:"bytes,5,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeIncarnationId string                 `protobuf:"bytes,6,opt,name=node_incarnation_id,json=nodeIncarnationId,proto3" json:"node_incarnation_id,omitempty"`
	NodeInstanceId    string                 `protobuf:"bytes,7,opt,name=node_instance_id,json=nodeInstanceId,proto3" json:"node_instance_id,omitempty"`
	ControllerEpoch   int64                  `protobuf:"varint,8,opt,name=controller_epoch,json=controllerEpoch,proto3" json:"controller_epoch,omitempty"`
	ControlEpoch      int64                  `protobuf:"varint,9,opt,name=control_epoch,json=controlEpoch,proto3" json:"control_epoch,omitempty"`
	ControlVersion    int64                  `protobuf:"varint,10,opt,name=control_version,json=controlVersion,proto3" json:"control_version,omitempty"`
	SessionId         string                 `protobuf:"bytes,11,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	ActorUserId       string                 `protobuf:"bytes,12,opt,name=actor_user_id,json=actorUserId,proto3" json:"actor_user_id,omitempty"`
	OperationId       string                 `protobuf:"bytes,13,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	ExecutionId       string                 `protobuf:"bytes,14,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	InputClosed       bool                   `protobuf:"varint,15,opt,name=input_closed,json=inputClosed,proto3" json:"input_closed,omitempty"`
	IssuedAtMs        int64                  `protobuf:"varint,16,opt,name=issued_at_ms,json=issuedAtMs,proto3" json:"issued_at_ms,omitempty"`
	ExpiresAtMs       int64                  `protobuf:"varint,17,opt,name=expires_at_ms,json=expiresAtMs,proto3" json:"expires_at_ms,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RuntimeBinding) Reset() {
	*x = RuntimeBinding{}
	mi := &file_ora_cloud_internal_v1_runtime_control_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeBinding) ProtoMessage() {}

func (x *RuntimeBinding) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_runtime_control_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeBinding.ProtoReflect.Descriptor instead.
func (*RuntimeBinding) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_runtime_control_proto_rawDescGZIP(), []int{0}
}

func (x *RuntimeBinding) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RuntimeBinding) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *RuntimeBinding) GetSandboxId() string {
	if x != nil {
		return x.SandboxId
	}
	return ""
}

func (x *RuntimeBinding) GetRuntimeGeneration() int64 {
	if x != nil {
		return x.RuntimeGeneration
	}
	return 0
}

func (x *RuntimeBinding) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *RuntimeBinding) GetNodeIncarnationId() string {
	if x != nil {
		return x.NodeIncarnationId
	}
	return ""
}

func (x *RuntimeBinding) GetNodeInstanceId() string {
	if x != nil {
		return x.NodeInstanceId
	}
	return ""
}

func (x *RuntimeBinding) GetControllerEpoch() int64 {
	if x != nil {
		return x.ControllerEpoch
	}
	return 0
}

func (x *RuntimeBinding) GetControlEpoch() int64 {
	if x != nil {
		return x.ControlEpoch
	}
	return 0
}

func (x *RuntimeBinding) GetControlVersion() int64 {
	if x != nil {
		return x.ControlVersion
	}
	return 0
}

func (x *RuntimeBinding) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *RuntimeBinding) GetActorUserId() string {
	if x != nil {
		return x.ActorUserId
	}
	return ""
}

func (x *RuntimeBinding) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *RuntimeBinding) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

func (x *RuntimeBinding) GetInputClosed() bool {
	if x != nil {
		return x.InputClosed
	}
	return false
}

func (x *RuntimeBinding) GetIssuedAtMs() int64 {
	if x != nil {
		return x.IssuedAtMs
	}
	return 0
}

func (x *RuntimeBinding) GetExpiresAtMs() int64 {
	if x != nil {
		return x.ExpiresAtMs
	}
	return 0
}

type ListRuntimeBindingsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Epoch         int64                  `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRuntimeBindingsRequest) Reset() {
	*x = ListRuntimeBindingsRequest{}
	mi := &file_ora_cloud_internal_v1_runtime_control_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRuntimeBindingsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRuntimeBindingsRequest) ProtoMessage() {}

func (x *ListRuntimeBindingsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_runtime_control_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRuntimeBindingsRequest.ProtoReflect.Descriptor instead.
func (*ListRuntimeBindingsRequest) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_runtime_control_proto_rawDescGZIP(), []int{1}
}

func (x *ListRuntimeBindingsRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

type ListRuntimeBindingsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bindings      []*RuntimeBinding      `protobuf:"bytes,1,rep,name=bindings,proto3" json:"bindings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRuntimeBindingsResponse) Reset() {
	*x = ListRuntimeBindingsResponse{}
	mi := &file_ora_cloud_internal_v1_runtime_control_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRuntimeBindingsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRuntimeBindingsResponse) ProtoMessage() {}

func (x *ListRuntimeBindingsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_runtime_control_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRuntimeBindingsResponse.ProtoReflect.Descriptor instead.
func (*ListRuntimeBindingsResponse) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_runtime_control_proto_rawDescGZIP(), []int{2}
}

func (x *ListRuntimeBindingsResponse) GetBindings() []*RuntimeBinding {
	if x != nil {
		return x.Bindings
	}
	return nil
}

type AcknowledgeRuntimeBindingRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	SubmissionId           string                 `protobuf:"bytes,1,opt,name=submission_id,json=submissionId,proto3" json:"submission_id,omitempty"`
	Epoch                  int64                  `protobuf:"varint,2,opt,name=epoch,proto3" json:"epoch,omitempty"`
	WorkspaceId            string                 `protobuf:"bytes,3,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	NodeInstanceId         string                 `protobuf:"bytes,4,opt,name=node_instance_id,json=nodeInstanceId,proto3" json:"node_instance_id,omitempty"`
	ControlEpoch           int64                  `protobuf:"varint,5,opt,name=control_epoch,json=controlEpoch,proto3" json:"control_epoch,omitempty"`
	ControlVersion         int64                  `protobuf:"varint,6,opt,name=control_version,json=controlVersion,proto3" json:"control_version,omitempty"`
	InputClosed            bool                   `protobuf:"varint,7,opt,name=input_closed,json=inputClosed,proto3" json:"input_closed,omitempty"`
	UnfinishedExecutionIds []string               `protobuf:"bytes,8,rep,name=unfinished_execution_ids,json=unfinishedExecutionIds,proto3" json:"unfinished_execution_ids,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *AcknowledgeRuntimeBindingRequest) Reset() {
	*x = AcknowledgeRuntimeBindingRequest{}
	mi := &file_ora_cloud_internal_v1_runtime_control_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeRuntimeBindingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeRuntimeBindingRequest) ProtoMessage() {}

func (x *AcknowledgeRuntimeBindingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_runtime_control_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeRuntimeBindingRequest.ProtoReflect.Descriptor instead.
func (*AcknowledgeRuntimeBindingRequest) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_runtime_control_proto_rawDescGZIP(), []int{3}
}

func (x *AcknowledgeRuntimeBindingRequest) GetSubmissionId() string {
	if x != nil {
		return x.SubmissionId
	}
	return ""
}

func (x *AcknowledgeRuntimeBindingRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *AcknowledgeRuntimeBindingRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *AcknowledgeRuntimeBindingRequest) GetNodeInstanceId() string {
	if x != nil {
		return x.NodeInstanceId
	}
	return ""
}

func (x *AcknowledgeRuntimeBindingRequest) GetControlEpoch() int64 {
	if x != nil {
		return x.ControlEpoch
	}
	return 0
}

func (x *AcknowledgeRuntimeBindingRequest) GetControlVersion() int64 {
	if x != nil {
		return x.ControlVersion
	}
	return 0
}

func (x *AcknowledgeRuntimeBindingRequest) GetInputClosed() bool {
	if x != nil {
		return x.InputClosed
	}
	return false
}

func (x *AcknowledgeRuntimeBindingRequest) GetUnfinishedExecutionIds() []string {
	if x != nil {
		return x.UnfinishedExecutionIds
	}
	return nil
}

type AcknowledgeRuntimeBindingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AcknowledgeRuntimeBindingResponse) Reset() {
	*x = AcknowledgeRuntimeBindingResponse{}
	mi := &file_ora_cloud_internal_v1_runtime_control_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AcknowledgeRuntimeBindingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcknowledgeRuntimeBindingResponse) ProtoMessage() {}

func (x *AcknowledgeRuntimeBindingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_runtime_control_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcknowledgeRuntimeBindingResponse.ProtoReflect.Descriptor instead.
func (*AcknowledgeRuntimeBindingResponse) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_runtime_control_proto_rawDescGZIP(), []int{4}
}

type GetRuntimeExecutionPermitRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Epoch          int64                  `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	WorkspaceId    string                 `protobuf:"bytes,2,opt,name=workspace_id,json=workspaceId,proto3" json:"workspace_id,omitempty"`
	NodeInstanceId string                 `protobuf:"bytes,3,opt,name=node_instance_id,json=nodeInstanceId,proto3" json:"node_instance_id,omitempty"`
	ControlEpoch   int64                  `protobuf:"varint,4,opt,name=control_epoch,json=controlEpoch,proto3" json:"control_epoch,omitempty"`
	ExecutionId    string                 `protobuf:"bytes,5,opt,name=execution_id,json=executionId,proto3" json:"execution_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetRuntimeExecutionPermitRequest) Reset() {
	*x = GetRuntimeExecutionPermitRequest{}
	mi := &file_ora_cloud_internal_v1_runtime_control_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuntimeExecutionPermitRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeExecutionPermitRequest) ProtoMessage() {}

func (x *GetRuntimeExecutionPermitRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_runtime_control_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeExecutionPermitRequest.ProtoReflect.Descriptor instead.
func (*GetRuntimeExecutionPermitRequest) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_runtime_control_proto_rawDescGZIP(), []int{5}
}

func (x *GetRuntimeExecutionPermitRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

func (x *GetRuntimeExecutionPermitRequest) GetWorkspaceId() string {
	if x != nil {
		return x.WorkspaceId
	}
	return ""
}

func (x *GetRuntimeExecutionPermitRequest) GetNodeInstanceId() string {
	if x != nil {
		return x.NodeInstanceId
	}
	return ""
}

func (x *GetRuntimeExecutionPermitRequest) GetControlEpoch() int64 {
	if x != nil {
		return x.ControlEpoch
	}
	return 0
}

func (x *GetRuntimeExecutionPermitRequest) GetExecutionId() string {
	if x != nil {
		return x.ExecutionId
	}
	return ""
}

type GetRuntimeExecutionPermitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Binding       *RuntimeBinding        `protobuf:"bytes,1,opt,name=binding,proto3" json:"binding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRuntimeExecutionPermitResponse) Reset() {
	*x = GetRuntimeExecutionPermitResponse{}
	mi := &file_ora_cloud_internal_v1_runtime_control_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRuntimeExecutionPermitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRuntimeExecutionPermitResponse) ProtoMessage() {}

func (x *GetRuntimeExecutionPermitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_runtime_control_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRuntimeExecutionPermitResponse.ProtoReflect.Descriptor instead.
func (*GetRuntimeExecutionPermitResponse) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_runtime_control_proto_rawDescGZIP(), []int{6}
}

func (x *GetRuntimeExecutionPermitResponse) GetBinding() *RuntimeBinding {
	if x != nil {
		return x.Binding
	}
	return nil
}

var File_ora_cloud_internal_v1_runtime_control_proto protoreflect.FileDescriptor

const file_ora_cloud_internal_v1_runtime_control_proto_rawDesc = "" +
	"\n" +
	"+ora/cloud/internal/v1/runtime_control.proto\x12\x15ora.cloud.internal.v1\"\xfc\x04\n" +
	"\x0eRuntimeBinding\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12\x1d\n" +
	"\n" +
	"sandbox_id\x18\x03 \x01(\tR\tsandboxId\x12-\n" +
	"\x12runtime_generation\x18\x04 \x01(\x03R\x11runtimeGeneration\x12\x17\n" +
	"\anode_id\x18\x05 \x01(\tR\x06nodeId\x12.\n" +
	"\x13node_incarnation_id\x18\x06 \x01(\tR\x11nodeIncarnationId\x12(\n" +
	"\x10node_instance_id\x18\a \x01(\tR\x0enodeInstanceId\x12)\n" +
	"\x10controller_epoch\x18\b \x01(\x03R\x0fcontrollerEpoch\x12#\n" +
	"\rcontrol_epoch\x18\t \x01(\x03R\fcontrolEpoch\x12'\n" +
	"\x0fcontrol_version\x18\n" +
	" \x01(\x03R\x0econtrolVersion\x12\x1d\n" +
	"\n" +
	"session_id\x18\v \x01(\tR\tsessionId\x12\"\n" +
	"\ractor_user_id\x18\f \x01(\tR\vactorUserId\x12!\n" +
	"\foperation_id\x18\r \x01(\tR\voperationId\x12!\n" +
	"\fexecution_id\x18\x0e \x01(\tR\vexecutionId\x12!\n" +
	"\finput_closed\x18\x0f \x01(\bR\vinputClosed\x12 \n" +
	"\fissued_at_ms\x18\x10 \x01(\x03R\n" +
	"issuedAtMs\x12\"\n" +
	"\rexpires_at_ms\x18\x11 \x01(\x03R\vexpiresAtMs\"2\n" +
	"\x1aListRuntimeBindingsRequest\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x03R\x05epoch\"`\n" +
	"\x1bListRuntimeBindingsResponse\x12A\n" +
	"\bbindings\x18\x01 \x03(\v2%.ora.cloud.internal.v1.RuntimeBindingR\bbindings\"\xd5\x02\n" +
	" AcknowledgeRuntimeBindingRequest\x12#\n" +
	"\rsubmission_id\x18\x01 \x01(\tR\fsubmissionId\x12\x14\n" +
	"\x05epoch\x18\x02 \x01(\x03R\x05epoch\x12!\n" +
	"\fworkspace_id\x18\x03 \x01(\tR\vworkspaceId\x12(\n" +
	"\x10node_instance_id\x18\x04 \x01(\tR\x0enodeInstanceId\x12#\n" +
	"\rcontrol_epoch\x18\x05 \x01(\x03R\fcontrolEpoch\x12'\n" +
	"\x0fcontrol_version\x18\x06 \x01(\x03R\x0econtrolVersion\x12!\n" +
	"\finput_closed\x18\a \x01(\bR\vinputClosed\x128\n" +
	"\x18unfinished_execution_ids\x18\b \x03(\tR\x16unfinishedExecutionIds\"#\n" +
	"!AcknowledgeRuntimeBindingResponse\"\xcd\x01\n" +
	" GetRuntimeExecutionPermitRequest\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x03R\x05epoch\x12!\n" +
	"\fworkspace_id\x18\x02 \x01(\tR\vworkspaceId\x12(\n" +
	"\x10node_instance_id\x18\x03 \x01(\tR\x0enodeInstanceId\x12#\n" +
	"\rcontrol_epoch\x18\x04 \x01(\x03R\fcontrolEpoch\x12!\n" +
	"\fexecution_id\x18\x05 \x01(\tR\vexecutionId\"d\n" +
	"!GetRuntimeExecutionPermitResponse\x12?\n" +
	"\abinding\x18\x01 \x01(\v2%.ora.cloud.internal.v1.RuntimeBindingR\abinding2\xa2\x03\n" +
	"\x15RuntimeControlService\x12u\n" +
	"\fListBindings\x121.ora.cloud.internal.v1.ListRuntimeBindingsRequest\x1a2.ora.cloud.internal.v1.ListRuntimeBindingsResponse\x12\x87\x01\n" +
	"\x12AcknowledgeBinding\x127.ora.cloud.internal.v1.AcknowledgeRuntimeBindingRequest\x1a8.ora.cloud.internal.v1.AcknowledgeRuntimeBindingResponse\x12\x87\x01\n" +
	"\x12GetExecutionPermit\x127.ora.cloud.internal.v1.GetRuntimeExecutionPermitRequest\x1a8.ora.cloud.internal.v1.GetRuntimeExecutionPermitResponseB\xe4\x01\n" +
	"\x19com.ora.cloud.internal.v1B\x13RuntimeControlProtoP\x01Z;github.com/wanglongan587/cloud/internal/controlpb;controlpb\xa2\x02\x03OCI\xaa\x02\x15Ora.Cloud.Internal.V1\xca\x02\x15Ora\\Cloud\\Internal\\V1\xe2\x02!Ora\\Cloud\\Internal\\V1\\GPBMetadata\xea\x02\x18Ora::Cloud::Internal::V1b\x06proto3"

var (
	file_ora_cloud_internal_v1_runtime_control_proto_rawDescOnce sync.Once
	file_ora_cloud_internal_v1_runtime_control_proto_rawDescData []byte
)

func file_ora_cloud_internal_v1_runtime_control_proto_rawDescGZIP() []byte {
	file_ora_cloud_internal_v1_runtime_control_proto_rawDescOnce.Do(func() {
		file_ora_cloud_internal_v1_runtime_control_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ora_cloud_internal_v1_runtime_control_proto_rawDesc), len(file_ora_cloud_internal_v1_runtime_control_proto_rawDesc)))
	})
	return file_ora_cloud_internal_v1_runtime_control_proto_rawDescData
}

var file_ora_cloud_internal_v1_runtime_control_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_ora_cloud_internal_v1_runtime_control_proto_goTypes = []any{
	(*RuntimeBinding)(nil),                    // 0: ora.cloud.internal.v1.RuntimeBinding
	(*ListRuntimeBindingsRequest)(nil),        // 1: ora.cloud.internal.v1.ListRuntimeBindingsRequest
	(*ListRuntimeBindingsResponse)(nil),       // 2: ora.cloud.internal.v1.ListRuntimeBindingsResponse
	(*AcknowledgeRuntimeBindingRequest)(nil),  // 3: ora.cloud.internal.v1.AcknowledgeRuntimeBindingRequest
	(*AcknowledgeRuntimeBindingResponse)(nil), // 4: ora.cloud.internal.v1.AcknowledgeRuntimeBindingResponse
	(*GetRuntimeExecutionPermitRequest)(nil),  // 5: ora.cloud.internal.v1.GetRuntimeExecutionPermitRequest
	(*GetRuntimeExecutionPermitResponse)(nil), // 6: ora.cloud.internal.v1.GetRuntimeExecutionPermitResponse
}
var file_ora_cloud_internal_v1_runtime_control_proto_depIdxs = []int32{
	0, // 0: ora.cloud.internal.v1.ListRuntimeBindingsResponse.bindings:type_name -> ora.cloud.internal.v1.RuntimeBinding
	0, // 1: ora.cloud.internal.v1.GetRuntimeExecutionPermitResponse.binding:type_name -> ora.cloud.internal.v1.RuntimeBinding
	1, // 2: ora.cloud.internal.v1.RuntimeControlService.ListBindings:input_type -> ora.cloud.internal.v1.ListRuntimeBindingsRequest
	3, // 3: ora.cloud.internal.v1.RuntimeControlService.AcknowledgeBinding:input_type -> ora.cloud.internal.v1.AcknowledgeRuntimeBindingRequest
	5, // 4: ora.cloud.internal.v1.RuntimeControlService.GetExecutionPermit:input_type -> ora.cloud.internal.v1.GetRuntimeExecutionPermitRequest
	2, // 5: ora.cloud.internal.v1.RuntimeControlService.ListBindings:output_type -> ora.cloud.internal.v1.ListRuntimeBindingsResponse
	4, // 6: ora.cloud.internal.v1.RuntimeControlService.AcknowledgeBinding:output_type -> ora.cloud.internal.v1.AcknowledgeRuntimeBindingResponse
	6, // 7: ora.cloud.internal.v1.RuntimeControlService.GetExecutionPermit:output_type -> ora.cloud.internal.v1.GetRuntimeExecutionPermitResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_ora_cloud_internal_v1_runtime_control_proto_init() }
func file_ora_cloud_internal_v1_runtime_control_proto_init() {
	if File_ora_cloud_internal_v1_runtime_control_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ora_cloud_internal_v1_runtime_control_proto_rawDesc), len(file_ora_cloud_internal_v1_runtime_control_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ora_cloud_internal_v1_runtime_control_proto_goTypes,
		DependencyIndexes: file_ora_cloud_internal_v1_runtime_control_proto_depIdxs,
		MessageInfos:      file_ora_cloud_internal_v1_runtime_control_proto_msgTypes,
	}.Build()
	File_ora_cloud_internal_v1_runtime_control_proto = out.File
	file_ora_cloud_internal_v1_runtime_control_proto_goTypes = nil
	file_ora_cloud_internal_v1_runtime_control_proto_depIdxs = nil
}
