// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ora/cloud/internal/v1/signals.proto

package controlpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WatchRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The caller's current lease epoch; a stale epoch fails with FAILED_PRECONDITION.
	Epoch         int64 `protobuf:"varint,1,opt,name=epoch,proto3" json:"epoch,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchRequest) Reset() {
	*x = WatchRequest{}
	mi := &file_ora_cloud_internal_v1_signals_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchRequest) ProtoMessage() {}

func (x *WatchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_signals_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchRequest.ProtoReflect.Descriptor instead.
func (*WatchRequest) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_signals_proto_rawDescGZIP(), []int{0}
}

func (x *WatchRequest) GetEpoch() int64 {
	if x != nil {
		return x.Epoch
	}
	return 0
}

// One signal per stream message.
type WatchResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Signal:
	//
	//	*WatchResponse_WorkAvailable
	//	*WatchResponse_Drain
	//	*WatchResponse_NodeAssignment
	//	*WatchResponse_OperationAvailable
	//	*WatchResponse_ThreadCommandAvailable
	Signal        isWatchResponse_Signal `protobuf_oneof:"signal"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchResponse) Reset() {
	*x = WatchResponse{}
	mi := &file_ora_cloud_internal_v1_signals_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchResponse) ProtoMessage() {}

func (x *WatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_signals_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchResponse.ProtoReflect.Descriptor instead.
func (*WatchResponse) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_signals_proto_rawDescGZIP(), []int{1}
}

func (x *WatchResponse) GetSignal() isWatchResponse_Signal {
	if x != nil {
		return x.Signal
	}
	return nil
}

func (x *WatchResponse) GetWorkAvailable() *WorkAvailable {
	if x != nil {
		if x, ok := x.Signal.(*WatchResponse_WorkAvailable); ok {
			return x.WorkAvailable
		}
	}
	return nil
}

func (x *WatchResponse) GetDrain() *Drain {
	if x != nil {
		if x, ok := x.Signal.(*WatchResponse_Drain); ok {
			return x.Drain
		}
	}
	return nil
}

func (x *WatchResponse) GetNodeAssignment() *NodeAssignment {
	if x != nil {
		if x, ok := x.Signal.(*WatchResponse_NodeAssignment); ok {
			return x.NodeAssignment
		}
	}
	return nil
}

func (x *WatchResponse) GetOperationAvailable() *OperationAvailable {
	if x != nil {
		if x, ok := x.Signal.(*WatchResponse_OperationAvailable); ok {
			return x.OperationAvailable
		}
	}
	return nil
}

func (x *WatchResponse) GetThreadCommandAvailable() *ThreadCommandAvailable {
	if x != nil {
		if x, ok := x.Signal.(*WatchResponse_ThreadCommandAvailable); ok {
			return x.ThreadCommandAvailable
		}
	}
	return nil
}

type isWatchResponse_Signal interface {
	isWatchResponse_Signal()
}

type WatchResponse_WorkAvailable struct {
	WorkAvailable *WorkAvailable `protobuf:"bytes,1,opt,name=work_available,json=workAvailable,proto3,oneof"`
}

type WatchResponse_Drain struct {
	Drain *Drain `protobuf:"bytes,2,opt,name=drain,proto3,oneof"`
}

type WatchResponse_NodeAssignment struct {
	NodeAssignment *NodeAssignment `protobuf:"bytes,3,opt,name=node_assignment,json=nodeAssignment,proto3,oneof"`
}

type WatchResponse_OperationAvailable struct {
	OperationAvailable *OperationAvailable `protobuf:"bytes,4,opt,name=operation_available,json=operationAvailable,proto3,oneof"`
}

type WatchResponse_ThreadCommandAvailable struct {
	ThreadCommandAvailable *ThreadCommandAvailable `protobuf:"bytes,5,opt,name=thread_command_available,json=threadCommandAvailable,proto3,oneof"`
}

func (*WatchResponse_WorkAvailable) isWatchResponse_Signal() {}

func (*WatchResponse_Drain) isWatchResponse_Signal() {}

func (*WatchResponse_NodeAssignment) isWatchResponse_Signal() {}

func (*WatchResponse_OperationAvailable) isWatchResponse_Signal() {}

func (*WatchResponse_ThreadCommandAvailable) isWatchResponse_Signal() {}

// Hints that work can be claimed; ownership is still decided by ClaimWork.
type WorkAvailable struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Set when Cloud knows which operation became claimable.
	OperationId   *string `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3,oneof" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkAvailable) Reset() {
	*x = WorkAvailable{}
	mi := &file_ora_cloud_internal_v1_signals_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkAvailable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkAvailable) ProtoMessage() {}

func (x *WorkAvailable) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_signals_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkAvailable.ProtoReflect.Descriptor instead.
func (*WorkAvailable) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_signals_proto_rawDescGZIP(), []int{2}
}

func (x *WorkAvailable) GetOperationId() string {
	if x != nil && x.OperationId != nil {
		return *x.OperationId
	}
	return ""
}

// Hints that a runtime Workspace operation became claimable after the transaction that queued it
// committed; ownership is still decided by ClaimOperation. An operation whose retry delay elapses
// has no such commit and is found by the periodic claim instead.
type OperationAvailable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationAvailable) Reset() {
	*x = OperationAvailable{}
	mi := &file_ora_cloud_internal_v1_signals_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationAvailable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationAvailable) ProtoMessage() {}

func (x *OperationAvailable) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_signals_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationAvailable.ProtoReflect.Descriptor instead.
func (*OperationAvailable) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_signals_proto_rawDescGZIP(), []int{3}
}

func (x *OperationAvailable) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

// Hints that a Thread command of a run became claimable after the transaction that persisted it
// committed; delivery is still driven by AgentRunService.ClaimThreadCommands.
type ThreadCommandAvailable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RunId         string                 `protobuf:"bytes,1,opt,name=run_id,json=runId,proto3" json:"run_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ThreadCommandAvailable) Reset() {
	*x = ThreadCommandAvailable{}
	mi := &file_ora_cloud_internal_v1_signals_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ThreadCommandAvailable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ThreadCommandAvailable) ProtoMessage() {}

func (x *ThreadCommandAvailable) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_signals_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ThreadCommandAvailable.ProtoReflect.Descriptor instead.
func (*ThreadCommandAvailable) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_signals_proto_rawDescGZIP(), []int{4}
}

func (x *ThreadCommandAvailable) GetRunId() string {
	if x != nil {
		return x.RunId
	}
	return ""
}

// The instance that sends it is about to stop. The holder stops claiming from it until a new Watch
// is established; Drain does not ask the holder to release its lease, and it never cancels user work
// or destroys sandboxes.
type Drain struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Drain) Reset() {
	*x = Drain{}
	mi := &file_ora_cloud_internal_v1_signals_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Drain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Drain) ProtoMessage() {}

func (x *Drain) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_signals_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Drain.ProtoReflect.Descriptor instead.
func (*Drain) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_signals_proto_rawDescGZIP(), []int{5}
}

// Reserved for control ownership changes of a Node; first-version Controllers only log it.
type NodeAssignment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NodeAssignment) Reset() {
	*x = NodeAssignment{}
	mi := &file_ora_cloud_internal_v1_signals_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NodeAssignment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NodeAssignment) ProtoMessage() {}

func (x *NodeAssignment) ProtoReflect() protoreflect.Message {
	mi := &file_ora_cloud_internal_v1_signals_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NodeAssignment.ProtoReflect.Descriptor instead.
func (*NodeAssignment) Descriptor() ([]byte, []int) {
	return file_ora_cloud_internal_v1_signals_proto_rawDescGZIP(), []int{6}
}

func (x *NodeAssignment) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

var File_ora_cloud_internal_v1_signals_proto protoreflect.FileDescriptor

const file_ora_cloud_internal_v1_signals_proto_rawDesc = "" +
	"\n" +
	"#ora/cloud/internal/v1/signals.proto\x12\x15ora.cloud.internal.v1\"$\n" +
	"\fWatchRequest\x12\x14\n" +
	"\x05epoch\x18\x01 \x01(\x03R\x05epoch\"\xb9\x03\n" +
	"\rWatchResponse\x12M\n" +
	"\x0ework_available\x18\x01 \x01(\v2$.ora.cloud.internal.v1.WorkAvailableH\x00R\rworkAvailable\x124\n" +
	"\x05drain\x18\x02 \x01(\v2\x1c.ora.cloud.internal.v1.DrainH\x00R\x05drain\x12P\n" +
	"\x0fnode_assignment\x18\x03 \x01(\v2%.ora.cloud.internal.v1.NodeAssignmentH\x00R\x0enodeAssignment\x12\\\n" +
	"\x13operation_available\x18\x04 \x01(\v2).ora.cloud.internal.v1.OperationAvailableH\x00R\x12operationAvailable\x12i\n" +
	"\x18thread_command_available\x18\x05 \x01(\v2-.ora.cloud.internal.v1.ThreadCommandAvailableH\x00R\x16threadCommandAvailableB\b\n" +
	"\x06signal\"H\n" +
	"\rWorkAvailable\x12&\n" +
	"\foperation_id\x18\x01 \x01(\tH\x00R\voperationId\x88\x01\x01B\x0f\n" +
	"\r_operation_id\"7\n" +
	"\x12OperationAvailable\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"/\n" +
	"\x16ThreadCommandAvailable\x12\x15\n" +
	"\x06run_id\x18\x01 \x01(\tR\x05runId\"\a\n" +
	"\x05Drain\")\n" +
	"\x0eNodeAssignment\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId2l\n" +
	"\x14ControlSignalService\x12T\n" +
	"\x05Watch\x12#.ora.cloud.internal.v1.WatchRequest\x1a$.ora.cloud.internal.v1.WatchResponse0\x01B\xdd\x01\n" +
	"\x19com.ora.cloud.internal.v1B\fSignalsProtoP\x01Z;github.com/wanglongan587/cloud/internal/controlpb;controlpb\xa2\x02\x03OCI\xaa\x02\x15Ora.Cloud.Internal.V1\xca\x02\x15Ora\\Cloud\\Internal\\V1\xe2\x02!Ora\\Cloud\\Internal\\V1\\GPBMetadata\xea\x02\x18Ora::Cloud::Internal::V1b\x06proto3"

var (
	file_ora_cloud_internal_v1_signals_proto_rawDescOnce sync.Once
	file_ora_cloud_internal_v1_signals_proto_rawDescData []byte
)

func file_ora_cloud_internal_v1_signals_proto_rawDescGZIP() []byte {
	file_ora_cloud_internal_v1_signals_proto_rawDescOnce.Do(func() {
		file_ora_cloud_internal_v1_signals_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ora_cloud_internal_v1_signals_proto_rawDesc), len(file_ora_cloud_internal_v1_signals_proto_rawDesc)))
	})
	return file_ora_cloud_internal_v1_signals_proto_rawDescData
}

var file_ora_cloud_internal_v1_signals_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_ora_cloud_internal_v1_signals_proto_goTypes = []any{
	(*WatchRequest)(nil),           // 0: ora.cloud.internal.v1.WatchRequest
	(*WatchResponse)(nil),          // 1: ora.cloud.internal.v1.WatchResponse
	(*WorkAvailable)(nil),          // 2: ora.cloud.internal.v1.WorkAvailable
	(*OperationAvailable)(nil),     // 3: ora.cloud.internal.v1.OperationAvailable
	(*ThreadCommandAvailable)(nil), // 4: ora.cloud.internal.v1.ThreadCommandAvailable
	(*Drain)(nil),                  // 5: ora.cloud.internal.v1.Drain
	(*NodeAssignment)(nil),         // 6: ora.cloud.internal.v1.NodeAssignment
}
var file_ora_cloud_internal_v1_signals_proto_depIdxs = []int32{
	2, // 0: ora.cloud.internal.v1.WatchResponse.work_available:type_name -> ora.cloud.internal.v1.WorkAvailable
	5, // 1: ora.cloud.internal.v1.WatchResponse.drain:type_name -> ora.cloud.internal.v1.Drain
	6, // 2: ora.cloud.internal.v1.WatchResponse.node_assignment:type_name -> ora.cloud.internal.v1.NodeAssignment
	3, // 3: ora.cloud.internal.v1.WatchResponse.operation_available:type_name -> ora.cloud.internal.v1.OperationAvailable
	4, // 4: ora.cloud.internal.v1.WatchResponse.thread_command_available:type_name -> ora.cloud.internal.v1.ThreadCommandAvailable
	0, // 5: ora.cloud.internal.v1.ControlSignalService.Watch:input_type -> ora.cloud.internal.v1.WatchRequest
	1, // 6: ora.cloud.internal.v1.ControlSignalService.Watch:output_type -> ora.cloud.internal.v1.WatchResponse
	6, // [6:7] is the sub-list for method output_type
	5, // [5:6] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_ora_cloud_internal_v1_signals_proto_init() }
func file_ora_cloud_internal_v1_signals_proto_init() {
	if File_ora_cloud_internal_v1_signals_proto != nil {
		return
	}
	file_ora_cloud_internal_v1_signals_proto_msgTypes[1].OneofWrappers = []any{
		(*WatchResponse_WorkAvailable)(nil),
		(*WatchResponse_Drain)(nil),
		(*WatchResponse_NodeAssignment)(nil),
		(*WatchResponse_OperationAvailable)(nil),
		(*WatchResponse_ThreadCommandAvailable)(nil),
	}
	file_ora_cloud_internal_v1_signals_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ora_cloud_internal_v1_signals_proto_rawDesc), len(file_ora_cloud_internal_v1_signals_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ora_cloud_internal_v1_signals_proto_goTypes,
		DependencyIndexes: file_ora_cloud_internal_v1_signals_proto_depIdxs,
		MessageInfos:      file_ora_cloud_internal_v1_signals_proto_msgTypes,
	}.Build()
	File_ora_cloud_internal_v1_signals_proto = out.File
	file_ora_cloud_internal_v1_signals_proto_goTypes = nil
	file_ora_cloud_internal_v1_signals_proto_depIdxs = nil
}
